INSERT INTO STORE_TB(STORE_ID,STORE_ADDRESS,STORE_NAME) VALUES (1,'Banglore','Apple Store');
INSERT INTO STORE_TB(STORE_ID,STORE_ADDRESS,STORE_NAME) VALUES (2,'Pune','iStore');
INSERT INTO PRODUCT_TB(PRODUCT_ID,ACTIVE,DESCRIPTION,PRICE,PRODUCT_NAME,RATING,STORE_ID) VALUES (101,TRUE,'DUMMY DESC',10000,'iPhone 13','4 STAR',1);
INSERT INTO PRODUCT_TB(PRODUCT_ID,ACTIVE,DESCRIPTION,PRICE,PRODUCT_NAME,RATING,STORE_ID) VALUES (102,TRUE,'DUMMY DESC',9983.5,'iPhone 10','4.5 STAR',2);
